{
 "title": "Traffic Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ip_textfield", "label": "test" },
   { "name": "username_textfield" }
  ]
 },
 "panels": [
  {
   "title": "Apply Username",
   "type": "speakyourcode-button-panel",
   "description": "Confirm change username",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "UPDATE users\nSET username = \"${username_textfield}\"\nWHERE src_ip = \"${ip_textfield}\";"
    }
   ]
  },
  {
   "title": "Average Total Traffic",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "sELECT \n    DATE_FORMAT(ts, \"%Y-%m-%d %H:00:00\") AS hour,\n    SUM(packet_length) AS total_traffic\nFROM \n    traffic_accounting.traffic_logs\nWHERE \n    ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n    hour\nORDER BY \n    hour;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    src_ip,\n    SUM(packet_length) AS total_traffic\nFROM\n    traffic_logs t\nWHERE\n    t.ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY\n    src_ip\nORDER BY\n    total_traffic DESC;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    UNIX_TIMESTAMP(DATE_FORMAT(t.ts, \"%Y-%m-%d %H:00:00\")) * 1000 AS time,\n    SUM(packet_length) AS total_traffic\nFROM \n    traffic_logs t\nWHERE \n    t.ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n    time\nORDER BY \n    time;"
    }
   ]
  },
  {
   "title": "Traffic Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    u.username,\r\n    t.src_ip,\r\n    t.dst_ip,\r\n    t.packet_length,\r\n    t.ts\r\nFROM \r\n    traffic_accounting.traffic_logs t\r\nLEFT JOIN\r\n     users u\r\nON\r\n    t.src_ip = u.src_ip\r\nWHERE\r\n    t.ts BETWEEN $__timeFrom()  AND  $__timeTo() ;\r\n  "
    }
   ]
  }
 ]
}